SELECT ESCOLA.NOME_ESCOLA, ((ENEM_ESCOLA.NU_MEDIA_CN + ENEM_ESCOLA.NU_MEDIA_CH +
    ENEM_ESCOLA.NU_MEDIA_LP + ENEM_ESCOLA.NU_MEDIA_MT + ENEM_ESCOLA.NU_MEDIA_REDACAO)/5) "Media"
FROM ENEM_ESCOLA
JOIN ESCOLA
    ON ENEM_ESCOLA.ESCOLA_ID = ESCOLA.ESCOLA_ID
WHERE ENEM_ESCOLA.ENEM_ID = "2018"
ORDER BY "Media" DESC;
