SELECT ENEM_ESCOLA.NU_MATRIULAS, ((ENEM_ESCOLA.NU_MEDIA_CN + ENEM_ESCOLA.NU_MEDIA_CH +
    ENEM_ESCOLA.NU_MEDIA_LP + ENEM_ESCOLA.NU_MEDIA_MT + ENEM_ESCOLA.NU_MEDIA_REDACAO)/5) "Media",
FROM ENEM_ESCOLA
ORDER BY "Media" DESC;
