--RESETAR TABLES:
--DROP TABLE ENEM_ESCOLA CASCADE CONSTRAINTS;
--DROP TABLE ESCOLA CASCADE CONSTRAINTS;
--DROP TABLE MUNICIPIO CASCADE CONSTRAINTS;

create table MUNICIPIO(
    MUN_ID number(10) CONSTRAINT mun_pk PRIMARY KEY,
    NOME VARCHAR2(120) NOT NULL,
    UF VARCHAR2(120) NOT NULL
);

create table ESCOLA(
    ESCOLA_ID number(10) CONSTRAINT escola_pk PRIMARY KEY,
    NOME_ESCOLA VARCHAR2(120) NOT NULL,
    MUN_ID number(10) NOT NULL,
    CONSTRAINT mun_id_fk FOREIGN KEY (MUN_ID) REFERENCES MUNICIPIO (MUN_ID)
);

create table ENEM_ESCOLA(
    ENEM_ID NUMBER(5),
    ESCOLA_ID number(3) REFERENCES ESCOLA (ESCOLA_ID),
    NU_MATRICULAS NUMBER,
    NU_PARTICIPANTES NUMBER,
    NU_PARTICIPANTES_ESPEC NUMBER,
    NU_MEDIA_CN NUMBER,
    NU_MEDIA_CH NUMBER,
    NU_MEDIA_LP NUMBER,
    NU_MEDIA_MT NUMBER,
    NU_MEDIA_REDACAO NUMBER,
    NU_MEDIA_OBJ NUMBER,
    NU_MEDIA_TOTAL NUMBER,
    CONSTRAINT enem_escola_pk PRIMARY KEY (ENEM_ID, ESCOLA_ID)
);
