SELECT CONTATO.COD_CONTATO, CONTATO.NOME_CONTATO, CLIENTE.NOME CLIENTE_NOME, SUM(ITEM_PEDIDO.QTD_VENDIDA*ITEM_PEDIDO.VALOR_VENDA) "VALOR_TOTAL"
FROM CONTATO
JOIN CONTATO_CLIENTE
    ON CONTATO_CLIENTE.COD_CONTATO = CONTATO.COD_CONTATO
JOIN CLIENTE
    ON CONTATO_CLIENTE.CPF = CLIENTE.CPF
JOIN PEDIDO 
    ON PEDIDO.CPF = CLIENTE.CPF
JOIN ITEM_PEDIDO
    ON PEDIDO.NUMERO_PEDIDO = ITEM_PEDIDO.NUMERO_PEDIDO
HAVING SUM(ITEM_PEDIDO.QTD_VENDIDA*ITEM_PEDIDO.VALOR_VENDA) > 1000
GROUP BY CLIENTE.CPF, CLIENTE.NOME, CONTATO.COD_CONTATO, CONTATO.NOME_CONTATO;
